using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Netfox.SourceGenerators;

/// <summary>
/// Turns <c>[RollbackState]</c> and friends on a member into the property-declaring interface the synchronizers read,
/// so the property paths come from the symbols instead of from hand-written strings.
/// <para>
/// The strings are the thing that rots: rename a property and <c>":position"</c> in a scene or in a
/// <c>GetRollbackStateProperties</c> body still compiles, then silently replicates nothing. An attribute on the
/// member cannot go stale, because renaming the member renames what is generated.
/// </para>
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class RollbackPropertiesGenerator : IIncrementalGenerator
{
    private const string Namespace = "Netfox";

    private static readonly Declaration[] Declarations =
    [
        new("RollbackStateAttribute", "IRollbackStateProperties", "GetRollbackStateProperties",
            "Marks a member as rollback state, replicated and rolled back by a RollbackSynchronizer."),
        new("RollbackInputAttribute", "IRollbackInputProperties", "GetRollbackInputProperties",
            "Marks a member as rollback input, gathered on its authority and sent to the peers that simulate it."),
        new("SynchronizedStateAttribute", "ISynchronizedStateProperties", "GetSynchronizedStateProperties",
            "Marks a member as state for a StateSynchronizer, replicated without rollback."),
        new("InterpolatedAttribute", "IInterpolatedProperties", "GetInterpolatedProperties",
            "Marks a member as interpolated between ticks by a TickInterpolator."),
    ];

    private static readonly DiagnosticDescriptor MustBePartial = new(
        "NFX001",
        "Netfox property attributes need a partial type",
        "'{0}' declares netfox properties, so it has to be declared partial",
        "Netfox",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("NetfoxPropertyAttributes.g.cs", SourceText.From(AttributeSource(), Encoding.UTF8)));

        foreach (var declaration in Declarations)
        {
            var current = declaration;
            var types = context.SyntaxProvider.ForAttributeWithMetadataName(
                    $"{Namespace}.{current.Attribute}",
                    static (node, _) => node is PropertyDeclarationSyntax,
                    (ctx, _) => Collect(ctx))
                .Where(static type => type is not null)
                .Collect();

            context.RegisterSourceOutput(types, (ctx, found) => Emit(ctx, current, found!));
        }
    }

    private static Found? Collect(GeneratorAttributeSyntaxContext context)
    {
        var member = context.TargetSymbol;
        if (member.ContainingType is not { } type) return null;
        return new Found(type, member.Name, context.TargetNode.GetLocation());
    }

    private static void Emit(SourceProductionContext context, Declaration declaration, ImmutableArray<Found> found)
    {
        foreach (var group in found.GroupBy<Found, INamedTypeSymbol>(item => item.Type, SymbolEqualityComparer.Default))
        {
            var type = group.Key;
            var members = group.Select(item => item.Member).Distinct().OrderBy(name => name, StringComparer.Ordinal).ToList();

            if (!IsPartial(type))
            {
                context.ReportDiagnostic(Diagnostic.Create(MustBePartial, group.First().Location, type.Name));
                continue;
            }

            var hint = $"{type.ToDisplayString().Replace('<', '_').Replace('>', '_')}.{declaration.Interface}.g.cs";
            context.AddSource(hint, SourceText.From(Render(type, declaration, members), Encoding.UTF8));
        }
    }

    private static bool IsPartial(INamedTypeSymbol type)
        => type.DeclaringSyntaxReferences.Any(reference =>
            reference.GetSyntax() is TypeDeclarationSyntax syntax &&
            syntax.Modifiers.Any(modifier => modifier.ValueText == "partial"));

    private static string Render(INamedTypeSymbol type, Declaration declaration, List<string> members)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/> Netfox.SourceGenerators");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        var containingNamespace = type.ContainingNamespace.IsGlobalNamespace
            ? null
            : type.ContainingNamespace.ToDisplayString();
        if (containingNamespace is not null)
        {
            builder.AppendLine($"namespace {containingNamespace};");
            builder.AppendLine();
        }

        var keyword = type.TypeKind == TypeKind.Struct ? "struct" : "class";
        builder.AppendLine($"partial {keyword} {type.Name} : global::{Namespace}.{declaration.Interface}");
        builder.AppendLine("{");
        builder.AppendLine($"    global::System.Collections.Generic.IEnumerable<string> global::{Namespace}.{declaration.Interface}.{declaration.Method}()");
        builder.AppendLine("        =>");
        builder.AppendLine("        [");
        foreach (var member in members)
            builder.AppendLine($"            \"{member}\",");
        builder.AppendLine("        ];");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static string AttributeSource()
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/> Netfox.SourceGenerators");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine($"namespace {Namespace};");
        builder.AppendLine();

        foreach (var declaration in Declarations)
        {
            builder.AppendLine("/// <summary>");
            builder.AppendLine($"/// {declaration.Summary}");
            builder.AppendLine("/// <para>The declaring type has to be partial; the generator implements");
            builder.AppendLine($"/// <see cref=\"{declaration.Interface}\"/> on it. Properties only: Godot exposes a");
            builder.AppendLine("/// partial class's properties to Get and Set, but not its plain fields.</para>");
            builder.AppendLine("/// </summary>");
            builder.AppendLine("[global::System.AttributeUsage(global::System.AttributeTargets.Property)]");
            builder.AppendLine($"public sealed class {declaration.Attribute} : global::System.Attribute;");
            builder.AppendLine();
        }

        return builder.ToString();
    }

    // Plain classes rather than records: netstandard2.0, which analyzers target, has no IsExternalInit for init setters
    private sealed class Declaration(string attribute, string @interface, string method, string summary)
    {
        public string Attribute { get; } = attribute;
        public string Interface { get; } = @interface;
        public string Method { get; } = method;
        public string Summary { get; } = summary;
    }

    private sealed class Found(INamedTypeSymbol type, string member, Location location)
    {
        public INamedTypeSymbol Type { get; } = type;
        public string Member { get; } = member;
        public Location Location { get; } = location;
    }
}
