using System.Collections.Immutable;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Netfox.SourceGenerators;

/// <summary>
/// Gives every spawnable class its own <c>Spawn</c>: <c>Crate.Spawn(at: transform)</c>, <c>Shot.Spawn(Muzzle)</c>,
/// <c>Player.Spawn(point, Colors.Blue, authority: 3)</c>. A class is spawnable when it carries <c>[Scene]</c> or
/// implements <c>ISpawnedWith&lt;T&gt;</c>.
/// <para>
/// The data a class needs is typed by its own <c>OnSpawned</c>: the generated parameter is optional only when that
/// method declares a default value itself, so a forgotten argument is a build error rather than a zero at run time.
/// </para>
/// <para>
/// Scenes come in as additional files. The generator maps each <c>.tscn</c> to the script on its root node, and fails
/// the build when a spawnable class has no scene or its script is the root of two.
/// </para>
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SpawnGenerator : IIncrementalGenerator
{
    private const string SceneAttribute = "Netfox.SceneAttribute";
    private const string SpawnedWith = "Netfox.ISpawnedWith`1";

    private static readonly DiagnosticDescriptor NoScene = new(
        "NFX003", "A spawnable class needs a scene",
        "'{0}' has no scene: add {1} or give [Scene] the path of the scene whose root is this class",
        "Netfox", DiagnosticSeverity.Error, true);

    private static readonly DiagnosticDescriptor TwoScenes = new(
        "NFX004", "A spawnable class is the root of more than one scene",
        "'{0}' is the root script of {1}: say which one with [Scene(\"res://...\")]",
        "Netfox", DiagnosticSeverity.Error, true);

    private static readonly DiagnosticDescriptor ArgumentNotVariant = new(
        "NFX005", "Spawn data has to fit in a Variant",
        "'{0}' is not a type Godot's Variant can hold, so it cannot travel with a spawn: use a Godot type, a primitive, a string, an enum or a Godot collection",
        "Netfox", DiagnosticSeverity.Error, true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource("NetfoxSceneAttribute.g.cs", SourceText.From("""
            // <auto-generated/> Netfox.SourceGenerators
            #nullable enable

            namespace Netfox;

            /// <summary>
            /// Makes a class spawnable with a generated <c>Spawn</c>. Without a path the scene is the one named after the
            /// class next to its script (<c>Crate.cs</c>, <c>Crate.tscn</c>).
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false)]
            public sealed class SceneAttribute : global::System.Attribute
            {
                public SceneAttribute(string? path = null) => Path = path;

                /// <summary>The <c>res://</c> path of the scene, or null for the one named after the class.</summary>
                public string? Path { get; }
            }
            """, Encoding.UTF8)));

        var classes = context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { BaseList: not null } or ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node) as INamedTypeSymbol)
            .Where(static type => type is not null && IsSpawnable(type))
            .Collect();

        var scenes = context.AdditionalTextsProvider
            .Where(static text => text.Path.EndsWith(".tscn", StringComparison.OrdinalIgnoreCase))
            .Select(static (text, token) => (text.Path, Content: text.GetText(token)?.ToString() ?? ""))
            .Collect();

        var projectDir = context.AnalyzerConfigOptionsProvider.Select(static (options, _) =>
            options.GlobalOptions.TryGetValue("build_property.GodotProjectDir", out var dir) ? dir : null);

        context.RegisterSourceOutput(classes.Combine(scenes).Combine(projectDir),
            static (ctx, input) => Emit(ctx, input.Left.Left!, input.Left.Right, input.Right));
    }

    private static bool IsSpawnable(INamedTypeSymbol type)
        => type.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == SceneAttribute)
           || type.AllInterfaces.Any(i => i.OriginalDefinition.ToDisplayString() == "Netfox.ISpawnedWith<TArgs>");

    private static readonly Regex ScriptResource = new(@"\[ext_resource[^\]]*type=""Script""[^\]]*path=""(?<path>[^""]+)""[^\]]*id=""(?<id>[^""]+)""", RegexOptions.Compiled);
    private static readonly Regex RootNode = new(@"\[node name=""[^""]*""(?![^\]]*parent=)[^\]]*\]\s*(?:[^\[]*?\n)*?script = ExtResource\(""(?<id>[^""]+)""\)", RegexOptions.Compiled);

    private static void Emit(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> classes,
        ImmutableArray<(string Path, string Content)> scenes, string? projectDir)
    {
        // Script res path -> scene res paths whose root node carries it
        var rootsOf = new Dictionary<string, List<string>>(StringComparer.Ordinal);
        if (projectDir is not null)
            foreach (var (path, content) in scenes)
            {
                var ids = ScriptResource.Matches(content).Cast<Match>().ToDictionary(m => m.Groups["id"].Value, m => m.Groups["path"].Value);
                var root = RootNode.Match(content);
                if (!root.Success || !ids.TryGetValue(root.Groups["id"].Value, out var script)) continue;
                if (!rootsOf.TryGetValue(script, out var list)) rootsOf[script] = list = new List<string>();
                list.Add(ToResPath(path, projectDir));
            }

        foreach (var type in classes.Distinct<INamedTypeSymbol?>(SymbolEqualityComparer.Default).OfType<INamedTypeSymbol>())
        {
            // A partial class can span files; Godot binds the script to the one named after the class
            var location = type.Locations.FirstOrDefault(l => System.IO.Path.GetFileNameWithoutExtension(l.SourceTree?.FilePath ?? "") == type.Name)
                           ?? type.Locations.FirstOrDefault();
            if (!type.DeclaringSyntaxReferences.Any(r => r.GetSyntax() is ClassDeclarationSyntax c && c.Modifiers.Any(m => m.ValueText == "partial")))
            {
                context.ReportDiagnostic(Diagnostic.Create(SyncedPropertiesGenerator.MustBePartial, location, type.Name));
                continue;
            }
            if (type.ContainingType is not null || type.IsGenericType)
            {
                context.ReportDiagnostic(Diagnostic.Create(SyncedPropertiesGenerator.MustBeTopLevel, location, type.Name));
                continue;
            }

            var explicitPath = type.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == SceneAttribute)?
                .ConstructorArguments.FirstOrDefault().Value as string;

            if (projectDir is not null && scenes.Length > 0 && explicitPath is null && location?.SourceTree?.FilePath is { } file)
            {
                var script = ToResPath(file, projectDir);
                var convention = script.Substring(0, script.Length - 3) + ".tscn";
                rootsOf.TryGetValue(script, out var roots);
                if (roots is { Count: > 1 })
                {
                    context.ReportDiagnostic(Diagnostic.Create(TwoScenes, location, type.Name, string.Join(", ", roots)));
                    continue;
                }
                if (!scenes.Any(s => ToResPath(s.Path, projectDir) == convention))
                {
                    context.ReportDiagnostic(Diagnostic.Create(NoScene, location, type.Name, convention));
                    continue;
                }
            }
            else if (projectDir is not null && scenes.Length > 0 && explicitPath is not null
                     && !scenes.Any(s => ToResPath(s.Path, projectDir) == explicitPath))
            {
                context.ReportDiagnostic(Diagnostic.Create(NoScene, location, type.Name, explicitPath));
                continue;
            }

            var spawnedWith = type.AllInterfaces.FirstOrDefault(i => i.OriginalDefinition.ToDisplayString() == "Netfox.ISpawnedWith<TArgs>");
            var args = spawnedWith?.TypeArguments[0];
            IParameterSymbol? parameter = null;
            if (args is not null)
            {
                if (!FitsVariant(args))
                {
                    context.ReportDiagnostic(Diagnostic.Create(ArgumentNotVariant, location, args.ToDisplayString()));
                    continue;
                }
                var onSpawned = type.GetMembers("OnSpawned").OfType<IMethodSymbol>()
                    .FirstOrDefault(m => m.Parameters.Length == 1 && SymbolEqualityComparer.Default.Equals(m.Parameters[0].Type, args));
                parameter = onSpawned?.Parameters[0];
            }

            context.AddSource($"{type.ToDisplayString()}.Spawn.g.cs",
                SourceText.From(Render(type, explicitPath, args, parameter), Encoding.UTF8));
        }
    }

    private static string ToResPath(string file, string projectDir)
    {
        var full = file.Replace('\\', '/');
        var dir = projectDir.Replace('\\', '/').TrimEnd('/') + "/";
        return full.StartsWith(dir, StringComparison.OrdinalIgnoreCase) ? "res://" + full.Substring(dir.Length) : full;
    }

    private static bool FitsVariant(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } nullable)
            return FitsVariant(nullable.TypeArguments[0]);
        if (type.TypeKind == TypeKind.Enum) return true;
        switch (type.SpecialType)
        {
            case SpecialType.System_Boolean:
            case SpecialType.System_Char:
            case SpecialType.System_SByte:
            case SpecialType.System_Byte:
            case SpecialType.System_Int16:
            case SpecialType.System_UInt16:
            case SpecialType.System_Int32:
            case SpecialType.System_UInt32:
            case SpecialType.System_Int64:
            case SpecialType.System_UInt64:
            case SpecialType.System_Single:
            case SpecialType.System_Double:
            case SpecialType.System_String:
                return true;
        }
        if (type is IArrayTypeSymbol array) return FitsVariant(array.ElementType);
        var ns = type.ContainingNamespace?.ToDisplayString();
        if (ns is "Godot" or "Godot.Collections") return true;
        for (var t = type.BaseType; t is not null; t = t.BaseType)
            if (t.ToDisplayString() == "Godot.GodotObject") return true;
        return false;
    }

    private static string Render(INamedTypeSymbol type, string? explicitPath, ITypeSymbol? args, IParameterSymbol? parameter)
    {
        var name = type.Name;
        var spatial = Inherits(type, "Godot.Node3D") ? "3D" : null;   // 3D only: see NetworkObject.UnsupportedReason
        var path = explicitPath is null ? "null" : "\"" + explicitPath.Replace("\"", "\\\"") + "\"";
        var argType = args?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var optional = parameter is { HasExplicitDefaultValue: true } ? " = " + DefaultLiteral(parameter) : "";
        var argParam = args is null ? "" : $"{argType} args{optional}, ";
        var toVariant = args is null ? "default" : ToVariant(args);

        var b = new StringBuilder();
        b.AppendLine("// <auto-generated/> Netfox.SourceGenerators");
        b.AppendLine("#nullable enable");
        b.AppendLine();
        if (!type.ContainingNamespace.IsGlobalNamespace) b.AppendLine($"namespace {type.ContainingNamespace.ToDisplayString()};").AppendLine();
        b.AppendLine($"partial class {name}" + (args is null ? "" : " : global::Netfox.Internal.ISpawnArgsReceiver"));
        b.AppendLine("{");
        const string tail = "global::Godot.Node? parent = null, int authority = 0)";
        if (spatial is not null)
        {
            var node = $"global::Godot.Node{spatial}";
            var transform = $"global::Godot.Transform{spatial}";
            b.AppendLine($"    /// <summary>Spawns this class's scene on every peer, where <paramref name=\"from\"/> is.</summary>");
            b.AppendLine($"    public static {name} Spawn({node} from, {argParam}{tail}");
            b.AppendLine($"        => global::Netfox.Spawning.Spawn<{name}>({path}, from.GlobalTransform, from, {toVariant}, parent, authority);");
            b.AppendLine();
            b.AppendLine($"    /// <summary>Spawns this class's scene on every peer at <paramref name=\"at\"/>, a global transform.</summary>");
            b.AppendLine($"    public static {name} Spawn({transform} at, {argParam}{tail}");
            b.AppendLine($"        => global::Netfox.Spawning.Spawn<{name}>({path}, at, null, {toVariant}, parent, authority);");
        }
        else
        {
            b.AppendLine($"    /// <summary>Spawns this class's scene on every peer.</summary>");
            b.AppendLine($"    public static {name} Spawn({argParam}{tail}");
            b.AppendLine($"        => global::Netfox.Spawning.Spawn<{name}>({path}, default, null, {toVariant}, parent, authority);");
        }
        if (args is not null)
        {
            b.AppendLine();
            b.AppendLine($"    void global::Netfox.Internal.ISpawnArgsReceiver.ReceiveSpawnArgs(global::Godot.Variant args) => OnSpawned({FromVariant(args)});");
        }
        b.AppendLine("}");
        return b.ToString();
    }

    private static bool Inherits(INamedTypeSymbol type, string baseName)
    {
        for (var t = type.BaseType; t is not null; t = t.BaseType)
            if (t.ToDisplayString() == baseName) return true;
        return false;
    }

    private static string ToVariant(ITypeSymbol args)
        => args is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T }
            ? "args is { } value ? global::Godot.Variant.From(value) : default"
            : "global::Godot.Variant.From(args)";

    private static string FromVariant(ITypeSymbol args)
        => args is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } nullable
            ? $"args.VariantType == global::Godot.Variant.Type.Nil ? null : args.As<{nullable.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>()"
            : $"args.As<{args.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>()";

    private static string DefaultLiteral(IParameterSymbol parameter)
        => parameter.ExplicitDefaultValue switch
        {
            null => "default",
            string s => "\"" + s.Replace("\"", "\\\"") + "\"",
            bool v => v ? "true" : "false",
            float f => f.ToString("R", System.Globalization.CultureInfo.InvariantCulture) + "f",
            double d => d.ToString("R", System.Globalization.CultureInfo.InvariantCulture) + "d",
            var v when parameter.Type.TypeKind == TypeKind.Enum => $"({parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}){v}",
            var v => Convert.ToString(v, System.Globalization.CultureInfo.InvariantCulture) ?? "default",
        };
}
