using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CrackNet.SourceGenerators;

/// <summary>
/// Turns <c>[Synced]</c> on a property into <c>ISyncedProperties</c> on its type, so the property paths come from the
/// symbols instead of from hand-written strings.
/// <para>
/// The strings are the thing that rots: rename a property and <c>":position"</c> in a scene still compiles, then
/// silently replicates nothing. An attribute on the member cannot go stale, because renaming the member renames what
/// is generated.
/// </para>
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SyncedPropertiesGenerator : IIncrementalGenerator
{
    private const string Namespace = "CrackNet";
    private const string Attribute = "SyncedAttribute";
    private const string Interface = "ISyncedProperties";

    internal static readonly DiagnosticDescriptor MustBePartial = new(
        "CRN001",
        "A CrackNet type has to be partial",
        "'{0}' declares synced properties or is spawnable, so it has to be declared partial",
        "CrackNet",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    internal static readonly DiagnosticDescriptor MustBeTopLevel = new(
        "CRN002",
        "A CrackNet type has to be top-level and non-generic",
        "'{0}' is nested or generic, which synced properties and spawning do not support: make it a top-level, non-generic type",
        "CrackNet",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("CrackNetSyncedAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        var found = context.SyntaxProvider.ForAttributeWithMetadataName(
                $"{Namespace}.{Attribute}",
                static (node, _) => node is PropertyDeclarationSyntax,
                static (ctx, _) => Collect(ctx))
            .Where(static item => item is not null)
            .Collect();

        context.RegisterSourceOutput(found, static (ctx, items) => Emit(ctx, items!));
    }

    private static Found? Collect(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol.ContainingType is not { } type) return null;

        var interpolate = true;
        foreach (var argument in context.Attributes[0].NamedArguments)
            if (argument.Key == "Interpolate" && argument.Value.Value is bool value)
                interpolate = value;

        return new Found(type, context.TargetSymbol.Name, interpolate, context.TargetNode.GetLocation());
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<Found> found)
    {
        foreach (var group in found.GroupBy<Found, INamedTypeSymbol>(item => item.Type, SymbolEqualityComparer.Default))
        {
            var type = group.Key;
            if (!IsPartial(type))
            {
                context.ReportDiagnostic(Diagnostic.Create(MustBePartial, group.First().Location, type.Name));
                continue;
            }
            // The generated declaration names neither the containing type nor type parameters, so it would declare a
            // separate, empty type and the real one would silently replicate nothing
            if (type.ContainingType is not null || type.IsGenericType)
            {
                context.ReportDiagnostic(Diagnostic.Create(MustBeTopLevel, group.First().Location, type.Name));
                continue;
            }

            var members = group.GroupBy(item => item.Member).Select(same => same.First())
                .OrderBy(item => item.Member, StringComparer.Ordinal).ToList();
            var hint = $"{type.ToDisplayString().Replace('<', '_').Replace('>', '_')}.{Interface}.g.cs";
            context.AddSource(hint, SourceText.From(Render(type, members), Encoding.UTF8));
        }
    }

    private static bool IsPartial(INamedTypeSymbol type)
        => type.DeclaringSyntaxReferences.Any(reference =>
            reference.GetSyntax() is TypeDeclarationSyntax syntax &&
            syntax.Modifiers.Any(modifier => modifier.ValueText == "partial"));

    private static string Render(INamedTypeSymbol type, List<Found> members)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/> CrackNet.SourceGenerators");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        if (!type.ContainingNamespace.IsGlobalNamespace)
        {
            builder.AppendLine($"namespace {type.ContainingNamespace.ToDisplayString()};");
            builder.AppendLine();
        }

        var keyword = type.TypeKind == TypeKind.Struct ? "struct" : "class";
        builder.AppendLine($"partial {keyword} {type.Name} : global::{Namespace}.{Interface}");
        builder.AppendLine("{");
        builder.AppendLine($"    global::System.Collections.Generic.IEnumerable<global::{Namespace}.SyncedProperty> global::{Namespace}.{Interface}.GetSyncedProperties()");
        builder.AppendLine("        =>");
        builder.AppendLine("        [");
        foreach (var member in members)
            builder.AppendLine($"            new(\"{member.Member}\", {(member.Interpolate ? "true" : "false")}),");
        builder.AppendLine("        ];");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private const string AttributeSource = """
        // <auto-generated/> CrackNet.SourceGenerators
        #nullable enable

        namespace CrackNet;

        /// <summary>
        /// Marks a property as state its NetworkObject sends while authoritative and plays back otherwise.
        /// <para>The declaring type has to be partial; the generator implements <see cref="ISyncedProperties"/> on it.
        /// Properties only: Godot exposes a partial class's properties to Get and Set, but not its plain fields.</para>
        /// </summary>
        [global::System.AttributeUsage(global::System.AttributeTargets.Property)]
        public sealed class SyncedAttribute : global::System.Attribute
        {
            /// <summary>
            /// Blend between samples on playback. Types with no in-between (bool, int, enums, strings, references) step
            /// regardless; set false on a continuous value that should step too.
            /// </summary>
            public bool Interpolate { get; set; } = true;
        }
        """;

    // Plain class rather than a record: netstandard2.0, which analyzers target, has no IsExternalInit for init setters
    private sealed class Found(INamedTypeSymbol type, string member, bool interpolate, Location location)
    {
        public INamedTypeSymbol Type { get; } = type;
        public string Member { get; } = member;
        public bool Interpolate { get; } = interpolate;
        public Location Location { get; } = location;
    }
}
